branch-defaults:
  master:
    environment: aws-service-r1-dev
    group_suffix: null
deploy:
  artifact: target/aws-service-r1-0.0.1-SNAPSHOT.jar
global:
  application_name: aws-service-r1
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
