name: CI Build
run-name: ${{ github.actor }} is doing some stuff 🚀

#on: [push]
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - run: echo "triggered by ${{ github.event_name }} event."
      - run: echo "branch name ${{ github.ref }}."

      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the ${{ runner.os }} server runner."

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - run: echo "job's status is ${{ job.status }}."